#!/bin/sh
# weird way of managing dotfiles i guess...
[ "$(id -u)" != "0" ] && exit 1 # ensure running as root

printf "\033[33mEnter name of your user.\033[0m \033[34mIf it doesn't exist,\033[0m \033[36mI'll just create it for you.\033[0m\n"
read userName

userHome="/home/${userName}"
[ ! -d "$userHome" ] && {
    useradd -m -G wheel "${userName}"
};

repoLocation="$userHome/.local/src/artix"
configFiles="$repoLocation/cfgs"
configArchiveLocation="$repoLocation/archive"

# install pkgs
pacman -Syu
{ find "${configFiles}/pkgs" -type f -exec cat {} + | pacman -S --needed --noconfirm -; } &&
    printf "\033[32mdone:\033[0m install packages\n"

# wallpaper
{
    rm -f "${userHome}/$(tr -d '\n' < "${configFiles}/wallpaperLocation")"
    curl -L "$(cat "${configFiles}/wallpaperUrl")" -o "${userHome}/$(cat "${configFiles}/wallpaperLocation")"
} &&
    printf "\033[32mdone:\033[0m install wallpaper\n"

# configs
find "${configFiles}/xdgConfigFiles" -type f | while IFS= read -r f; do
    val="$(tr -d '\n' < "$f")"
    [ -e "${configArchiveLocation}/${val}" ] || {
	printf "\033[31mwarning:\033[0m "${configArchiveLocation}/${val}" is not stored in archive. Skipping.\n"
	continue
    }
    
    target="${userHome}/${val}"
    if [ -e "$target" ] && [ -n "$val" ]; then
	rm -rf "$target"
    fi
    
    mkdir -p "${userHome}/$(dirname "$val")"
    cp -rf "${configArchiveLocation}/${val}" "${target}"
done

# ensure user owns everything
chown "${userName}:${userName}" -R "${userHome}"

# finish
printf "\033[32mran necessary commands, but success is unknown:\033[0m install configurations\n"
